#!/bin/bash
#
# Init file for TOMCAT server daemon
#
# chkconfig: 2345 97 02
# description: TOMCAT server daemon
#
# processname: tomcat

# source function library
. /etc/rc.d/init.d/functions

RETVAL=0
prog="tomcat"
PROG=/usr/local/tomcat/tomcat
WD=/usr/local/tomcat/current
USER=tomcat
JAVA_HOME=/usr/java/current
CATALINA_HOME=/usr/local/tomcat/current
classpath=$JAVA_HOME/lib/tools.jar:$CATALINA_HOME/bin/bootstrap.jar:$CATALINA_HOME/bin/commons-logging-api.jar
OPTIONS=$"$JAVA_HOME/bin/java -Xmx512M -Djava.awt.headless=true -Djava.endorsed.dirs=$CATALINA_HOME/common/endorsed -classpath $classpath -Dcatalina.base=$CATALINA_HOME -Dcatalina.home=$CATALINA_HOME -Djava.io.tmpdir=$CATALINA_HOME/temp org.apache.catalina.startup.Bootstrap start >> "$CATALINA_HOME"/logs/catalina.out"

start()
{
	# Check for server already running...
	pid=`pidof -s $prog`
	if [ $pid ]
	then
		echo $"$prog already running."
	else
		echo -n $"Starting $prog:"
		su -l $USER -s /bin/bash -c "cd $WD && $PROG $OPTIONS &" && success || failure
		RETVAL=$?
		[ "$RETVAL" = 0 ] && touch /var/lock/subsys/$prog
		echo
	fi
}

stop()
{
	echo -n $"Stopping $prog:"
	killproc $PROG -TERM
	RETVAL=$?
	[ "$RETVAL" = 0 ] && rm -f /var/lock/subsys/$prog
	echo
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart)
		stop
		start
		;;
	status)
		status $PROG
		RETVAL=$?
		;;
	*)
		echo $"Usage: $0 {start|stop|restart|status}"
		RETVAL=1
esac
exit $RETVAL
